name: sitegen
description: Static site generator for Dart, webserver included.
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-sitegen

version: 0.0.4

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/dartpad.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  sitegen:

dependencies:
  browser: any

  logging: any
  logging_handlers: any
  console_log_handler: any

  validate: any

  args: any
  path: any
  yaml: any
  markdown: any
  mustache: any
  intl: any
  http_server: any

dev_dependencies:
  unittest: any