name: 'simple'
version: 0.0.1
description: >
  An absolute bare-bones web app.

#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:

  browser: ^0.10.0
  mdl: ^1.0.0

  di: ^3.3.0

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - di
  - dart_to_js_script_rewriter

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]
